sudo: required
language: python

python:
  - "2.7"

before_script:
  - pip install pytest
  - pip install numpy
  - pip install opencv-python
  - pip install -r requirements.txt
  - python origami-lib/test/server_textimageinput.py &
  - sleep 1

script:
  - cd origami-lib/test/
  - pytest

cache: pip
