sudo: required
language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - pip install -U pip

install:
  - pip install opencv-python
  - pip install numpy
  - pip install -r requirements.txt

cache:
  directories:
    - origami-lib
