DEMO_DEPLOYMENT_TYPE = ["gh", "nongh"]

TOKEN_FORMAT = "nongh:0.0.0.0:1814173:5001:9001:0.0.0.0"

ORIGAMI_DEFAULT_EVENT_ROUTE = "/event"

INPUT_IMAGE_ARRAY_FILEPATH_MODE = "file_path"
INPUT_IMAGE_ARRAY_NPARRAY_MODE = "numpy_array"

